In [97]:
import os.path 
import numpy as np
import pandas as pd
import csv

from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,accuracy_score
    
import tensorflow as tf

from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.utils import to_categorical

In [ ]:
directory =os.path.dirname(os.getcwd())

In [79]:
Fashion=pd.read_csv(directory+'\\Data\\\fashion-mnist_train.csv')

In [80]:
Fashion_labels=Fashion.pop('label')

In [81]:
Fashion_labels=to_categorical(Fashion_labels)

In [82]:
Fashion = Fashion.values.reshape((len(Fashion), 28, 28,1))

In [66]:
Fashion_labels=Fashion_labels[0:125]
Fashion=Fashion[0:125]

In [83]:
Fashion_train,Fashion_test,Labels_train,Labels_test=train_test_split(Fashion,Fashion_labels,train_size=0.8,test_size=0.2,random_state=42)
Fashion_val,Fashion_test,Labels_val,Labels_test=train_test_split(Fashion_test,Labels_test,train_size=0.5,test_size=0.5,random_state=42)

# Model definition

In [84]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Conv2D(8,kernel_size=5, padding="same",activation='relu', input_shape=(28,28,1)))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.Conv2D(4,kernel_size=3,activation='relu', padding="same"))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.Conv2D(2,kernel_size=3, activation='relu',padding="same"))
model.add(tf.keras.layers.MaxPooling2D())
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(10,activation="softmax"))

In [85]:
opt=tf.keras.optimizers.SGD(0.001, momentum=0.9)
model.compile(optimizer=opt, loss='mse')

In [86]:
EVALUATION_INTERVAL = 3000
EPOCHS = 12

In [87]:
History=model.fit(Fashion_train, Labels_train,
  epochs=EPOCHS, validation_data=(Fashion_val,Labels_val))

Train on 48000 samples, validate on 6000 samples
Epoch 1/12
48000/48000 [==============================] - 18s 369us/sample - loss: 0.0882 - val_loss: 0.0849
Epoch 2/12
48000/48000 [==============================] - 17s 353us/sample - loss: 0.0825 - val_loss: 0.0788
Epoch 3/12
48000/48000 [==============================] - 17s 361us/sample - loss: 0.0768 - val_loss: 0.0755
Epoch 4/12
48000/48000 [==============================] - 17s 354us/sample - loss: 0.0744 - val_loss: 0.0734
Epoch 5/12
48000/48000 [==============================] - 17s 357us/sample - loss: 0.0726 - val_loss: 0.0689
Epoch 6/12
48000/48000 [==============================] - 17s 357us/sample - loss: 0.0657 - val_loss: 0.0637
Epoch 7/12
48000/48000 [==============================] - 18s 365us/sample - loss: 0.0628 - val_loss: 0.0617
Epoch 8/12
48000/48000 [==============================] - 17s 358us/sample - loss: 0.0602 - val_loss: 0.0594
Epoch 9/12
48000/48000 [==============================] - 17s 355us/sample - lo

# Test Analysis

In [88]:
test_predictions=model.predict(Fashion_test)

In [89]:
test_predictions.round(),Labels_test

(array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]], dtype=float32),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [1., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 1., 0., 0.]], dtype=float32))

In [92]:
Labels_test.argmax(axis=1)

array([3, 7, 6, ..., 0, 5, 7], dtype=int64)

In [94]:
confusion_matrix(test_predictions.argmax(axis=1),Labels_test.argmax(axis=1))

array([[428,   0,   3,  27,   7,  11, 118,   0,   0,   0],
       [  9, 504,  30,   9,  18,  21,  33,   0,   4,   1],
       [ 16,   3, 102,   7,  23,  22,  56,   1,   1,   0],
       [ 54,  56,  13, 458,  63,   8,  31,   1,   9,   1],
       [ 67,  16, 420,  81, 472,  12, 320,   0,  37,  20],
       [  5,   0,   2,   6,   0, 252,  11,  24,   9,  22],
       [  7,   2,  12,   2,   6,  15,  18,   0,   4,   1],
       [  5,   0,   0,   1,   1, 100,   5, 547,   5,  50],
       [  7,   1,   9,   6,   7,  46,  17,   6, 485,   0],
       [  1,   0,   4,   1,   2,  90,  13,  56,  23, 521]], dtype=int64)

In [98]:
accuracy_score(test_predictions.argmax(axis=1),Labels_test.argmax(axis=1))

0.6311666666666667